baseURL = 'https://www.waitwhatsthat.com/'
languageCode = 'en-us'
title = "Wait What's That?"
theme = 'ananke'
buildDrafts = false
buildFuture = false
buildExpired = false
enableRobotsTXT = true

[params]
  description = "Discovering remarkable food and experiences around the world"
  mainSections = ["posts"]

[services.disqus]
  shortname = "waitwhatsthat"

[menu]
  [[menu.main]]
    name = "Archive"
    url = "/posts/"
    weight = 5
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 10
  [[menu.main]]
    name = "Locations"
    url = "/locations/"
    weight = 15
  [[menu.main]]
    name = "About"
    url = "/about-us/"
    weight = 20

[taxonomies]
  tag = "tags"
  location = "locations"
